In [1]:
# Import dependencies
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
# List all files to be combined
file_compliation = ['data/202107.csv', 'data/202108.csv', 'data/202109.csv', 'data/202110.csv', 'data/202111.csv', 'data/202112.csv',
    'data/202201.csv', 'data/202202.csv', 'data/202203.csv', 'data/202204.csv', 'data/202205.csv', 'data/202206.csv', 'data/202207.csv', 'data/202208.csv', 'data/202209.csv', 'data/202210.csv', 'data/202211.csv', 'data/202212.csv',
        'data/202301.csv', 'data/202302.csv', 'data/202303.csv']

# Create an empty list to store each df
df_list = []

# Loop
for file in file_compliation:
    df = pd.read_csv(file)
    df_list.append(df)

# Concatenate all dataframes into one
# https://www.geeksforgeeks.org/how-to-concatenate-two-or-more-pandas-dataframes/
df = pd.concat(df_list)

df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C9446233AFAB8896,classic_bike,2021-07-15 19:27:25,2021-07-15 19:27:35,Journal Square,JC103,Journal Square,JC103,40.733670,-74.062500,40.733670,-74.062500,member
1,0C3D69370BE39992,electric_bike,2021-07-22 06:41:54,2021-07-22 06:42:03,Journal Square,JC103,Journal Square,JC103,40.733670,-74.062500,40.733670,-74.062500,member
2,3B0390B706281176,classic_bike,2021-07-19 06:36:13,2021-07-19 06:38:18,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.726012,-74.050389,40.725289,-74.045572,member
3,9AFBC07247ABE507,classic_bike,2021-07-08 06:33:45,2021-07-08 06:35:53,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.726012,-74.050389,40.725289,-74.045572,member
4,ADB073F7FFC372D3,classic_bike,2021-07-21 07:33:49,2021-07-21 08:00:14,14 St Ferry - 14 St & Shipyard Ln,HB202,Columbus Dr at Exchange Pl,JC106,40.752961,-74.024353,40.716870,-74.032810,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63067,BF0032DA4A305161,classic_bike,2023-03-19 16:25:24,2023-03-19 16:33:20,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,member
63068,32172F9BEF8D56A2,classic_bike,2023-03-22 16:14:15,2023-03-22 16:20:28,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
63069,6FCF0C7C1E254341,electric_bike,2023-03-19 02:16:02,2023-03-19 02:21:15,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
63070,34DFBEB02424B55E,electric_bike,2023-03-30 20:09:24,2023-03-30 20:15:08,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
63071,A235AD010540ACA2,classic_bike,2023-03-17 17:53:28,2023-03-17 17:59:43,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual

In [3]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [4]:
## Formatting

# Correcting datatypes
df['started_at'] = pd.to_datetime(df['started_at'], format = "%Y-%m-%d %H:%M:%S")
df['ended_at'] = pd.to_datetime(df['ended_at'], format = "%Y-%m-%d %H:%M:%S")

# Check 
df.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [5]:
## Formatting

# Lat/Lon decimals
df['start_lat'] = df['start_lat'].round(decimals=5)
df['start_lng'] = df['start_lng'].round(decimals=5)
df['end_lat'] = df['end_lat'].round(decimals=5)
df['end_lng'] = df['end_lng'].round(decimals=5)

# Check
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C9446233AFAB8896,classic_bike,2021-07-15 19:27:25,2021-07-15 19:27:35,Journal Square,JC103,Journal Square,JC103,40.73367,-74.06250,40.73367,-74.06250,member
1,0C3D69370BE39992,electric_bike,2021-07-22 06:41:54,2021-07-22 06:42:03,Journal Square,JC103,Journal Square,JC103,40.73367,-74.06250,40.73367,-74.06250,member
2,3B0390B706281176,classic_bike,2021-07-19 06:36:13,2021-07-19 06:38:18,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.72601,-74.05039,40.72529,-74.04557,member
3,9AFBC07247ABE507,classic_bike,2021-07-08 06:33:45,2021-07-08 06:35:53,Brunswick & 6th,JC081,Jersey & 6th St,JC027,40.72601,-74.05039,40.72529,-74.04557,member
4,ADB073F7FFC372D3,classic_bike,2021-07-21 07:33:49,2021-07-21 08:00:14,14 St Ferry - 14 St & Shipyard Ln,HB202,Columbus Dr at Exchange Pl,JC106,40.75296,-74.02435,40.71687,-74.03281,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63067,BF0032DA4A305161,classic_bike,2023-03-19 16:25:24,2023-03-19 16:33:20,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.73879,-74.03930,40.74816,-74.03245,member
63068,32172F9BEF8D56A2,classic_bike,2023-03-22 16:14:15,2023-03-22 16:20:28,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.73879,-74.03930,40.74816,-74.03245,casual
63069,6FCF0C7C1E254341,electric_bike,2023-03-19 02:16:02,2023-03-19 02:21:15,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.73879,-74.03930,40.74816,-74.03245,casual
63070,34DFBEB02424B55E,electric_bike,2023-03-30 20:09:24,2023-03-30 20:15:08,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.73879,-74.03930,40.74816,-74.03245,casual
63071,A235AD010540ACA2,classic_bike,2023-03-17 17:53:28,2023-03-17 17:59:43,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.73879,-74.03930,40.74816,-74.03245,casual

In [6]:
# Save df to csv file
df.to_csv('data/citibike.csv', index = False)